
# Laboratorio 6.2
Elaborado por Oscar Franco-Bedoya

Proyecto Mision TIC 2021

# Objetivo
En este laboratorio vamos a practicar funciones generales con matrices y busquedas.

## Definición y recorridos de matrices

In [1]:
M=[[3,8,1],[-1,4,7],[3,2,0],[9,12,65]] # Definición de una matriz M(4x3)

def recorrido_filas(M):
  for i in range(0,4): # Recorrido por filas
    for j in range(0,3):
      print(M[i][j], end = '\t')
    print('\n')


def recorrido_columnas(M):
  for i in range(0,4): # Recorrido por filas
    for j in range(0,3):
      print(M[i][j], end = '\t')
    print('\n')


#----------------------------------------------------------------------------
recorrido_filas(M)
print("------------------")
recorrido_columnas(M)


3	8	1	

-1	4	7	

3	2	0	

9	12	65	

------------------
3	8	1	

-1	4	7	

3	2	0	

9	12	65	



# Búsquedas 

Se presentan dos funciones de búsqueda, unas para listas de valores básicos y otra para listas de tuplas.


In [7]:
personas=['1001458257','100225897','10283475','35236587','568745218']

# Retorna el índice de un elemento dado
def buscar_id_2(id_s):
  return personas.index(id_s)


# Retorna el índice de un elemento dado de manera segura
def buscar_id_segura(id_s):
  try:
    return personas.index(id_s)
  except ValueError:
    return None

# Búsqueda secuencial de un elemento de la lista
def buscar_id(id_s):
  for id in personas:
    if id==id_s:
      return id

personas=[('1001458257',True),('100225897',True),('10283475',False),('35236587',True),('568745218',False)]

# Búsqueda secuencial de un grupo de elementos de la lista
def vacunados():
  lista_vacunados=[]
  for p in personas:
    if p[1]==True:
      lista_vacunados.append(p)
  return lista_vacunados



# Prueba los métodos anteriores 

In [9]:
# Codifica el algoritmo pincipal aqui
personas=['1001458257','100225897','10283475','35236587','568745218']

# Retorna el índice de un elemento dado
def buscar_id_2(id_s):
  return personas.index(id_s)


def buscar_id_segura(id_s):
  try:
    return personas.index(id_s)
  except ValueError:
    return None
  
  
def buscar_id(id_s):
  for id in personas:
    if id==id_s:
      return id  


print(buscar_id_2('35236587'))
print(buscar_id_segura('XXXXX'))
print(buscar_id('35236587'))



3
None
35236587


In [11]:
personas=[('1001458257',True),('100225897',True),('10283475',False),('35236587',True),('568745218',False)]

# Búsqueda secuencial de un grupo de elementos de la lista
def vacunados():
  lista_vacunados=[]
  for p in personas:
    if p[1]==True:
      lista_vacunados.append(p)
  return lista_vacunados


print(vacunados())

[('1001458257', True), ('100225897', True), ('35236587', True)]


# Entrenador Ajedrez

Vamos a realizar una aplicación que muestre los movimientos de las diferentes figuras en un tablero de ajedrez.


# Movimiento de la torre
La torre se mueve en líneas rectas en las columnas y filas del tablero en donde se encuentre ubicada, sin embargo no puede saltar figuras adversarias o aliadas.

Vamos a suponer que el tablero está vacío y que nos dan una posición valida de la torre en el tablero. La función debe mostrar las casillas en las cuales se puede mover la torre.



In [26]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_torre(tablero, posicion):
    """ 
    Parameters
    ----------
    tablero: [[][]] 
      Matriz de dos dimensiones con valores booleanos en False
    posicion: (,) 
      Tupla con la posición de la torre en el tablero  
    Returns
    -------
    tablero
      el tablero con las posiciones validas para el movimiento en True    
    """ 
    for i in range(8):   #asigna la fila
        tablero[posicion.f, i] = True

    for i in range(8): #asigna la columna
        tablero[i, posicion.c] = True


posicion = PosicionTablero(4, 2)
ataque_torre(tablero, posicion)
tablero

array([[False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False]])

# Ejercicio

Desarrolla las funciones para las demas figuras
*   Reina
*   Alfil
*   Caballo 
*   Peon
*   Rey
---
FIN LABORATORIO
---



# Reina

In [33]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_reina(tablero, posicion):
    
    for i in range(8):
        tablero[posicion.f, i] = True

    for i in range(8):
        tablero[i, posicion.c] = True
    
    
    for i in range(8):
        if posicion.f + i < 8 and posicion.c + i < 8:
            tablero[posicion.f + i, posicion.c + i] = True
        else:
            break
        
    for i in range(8):
        if posicion.c - i >= 0 and posicion.c - i >= 0:
            tablero[posicion.f - i, posicion.c - i] = True
        else:
            break
        
        
    for i in range(8):
        if posicion.f + i < 8 and posicion.c - i >= 0:
            tablero[posicion.f + i, posicion.c - i] = True
        else:
            break
        
        
    for i in range(8):
        if posicion.f - i >= 0 and posicion.c + i < 8:
            tablero[posicion.f - i, posicion.c + i] = True
        
        
posicion = PosicionTablero(2, 2)
ataque_reina(tablero, posicion)
tablero


array([[ True, False,  True, False,  True, False, False, False],
       [False,  True,  True,  True, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False, False, False, False],
       [ True, False,  True, False,  True, False, False, False],
       [False, False,  True, False, False,  True, False, False],
       [False, False,  True, False, False, False,  True, False],
       [False, False,  True, False, False, False, False,  True]])

# Alfil

In [31]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_alfil(tablero, posicion):
    for i in range(8):   #asigna la fila
        if posicion.f + i < 8 and posicion.c + i < 8:
            tablero[posicion.f + i, posicion.c + i] = True
        else:
            break
        
    for i in range(8):
        if posicion.c - i >= 0 and posicion.c - i >= 0:
            tablero[posicion.f - i, posicion.c - i] = True
        else:
            break
        
        
    for i in range(8):
        if posicion.f + i < 8 and posicion.c - i >= 0:
            tablero[posicion.f + i, posicion.c - i] = True
        else:
            break
        
        
    for i in range(8):
        if posicion.f - i >= 0 and posicion.c + i < 8:
            tablero[posicion.f - i, posicion.c + i] = True
        
        
posicion = PosicionTablero(2, 2)
ataque_alfil(tablero, posicion)
tablero


array([[ True, False, False, False,  True, False, False, False],
       [False,  True, False,  True, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False,  True, False,  True, False, False, False, False],
       [ True, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

# Caballo

In [21]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_caballo(tablero, posicion):
    tablero[posicion.f, posicion.c] = True
    if posicion.f + 1 < 8 and posicion.f - 1 >= 0 and posicion.c + 3 < 8:
        tablero[posicion.f + 1, posicion.c + 3] = True
        tablero[posicion.f - 1, posicion.c + 3] = True
        
    if posicion.f + 1 < 8 and posicion.f - 1 >= 0 and posicion.c - 3 >= 0:
        tablero[posicion.f + 1, posicion.c - 3] = True
        tablero[posicion.f - 1, posicion.c - 3] = True
        
    if posicion.f + 3 < 8 and posicion.c + 1 < 8 and posicion.c - 1 >= 0:
        tablero[posicion.f + 3, posicion.c + 1] = True
        tablero[posicion.f + 3 , posicion.c - 1] = True
        
    if posicion.f - 3 >= 0 and posicion.c + 1 < 8 and posicion.c - 1 >= 0:
        tablero[posicion.f - 3, posicion.c + 1] = True
        tablero[posicion.f - 3, posicion.c - 1] = True
        
        
posicion = PosicionTablero(3, 3)
ataque_caballo(tablero, posicion)
tablero


array([[False, False,  True, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False,  True, False],
       [False, False, False,  True, False, False, False, False],
       [ True, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [26]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_peon(tablero, posicion):
    tablero[posicion.f, posicion.c] = True
    if posicion.f - 1 >= 0:
        tablero[posicion.f - 1, posicion.c] = True
        
        
        
posicion = PosicionTablero(3, 3)
ataque_peon(tablero, posicion)
tablero


array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [29]:
import numpy as np
from collections import namedtuple

# aprovechamos las funciones de la librería NumPy para crear una matriz de 8 x 8 inicializada en False 
tablero = np.array([[False] * 8] *8 ) 

# Definimos una tupla para la posición de la torre
PosicionTablero = namedtuple('PosicionTablero', ['f', 'c']) 


def ataque_rey(tablero, posicion):
    tablero[posicion.f, posicion.c] = True
    if posicion.f - 1 < 8 or posicion.f + 1 >= 0 :
        tablero[posicion.f - 1, posicion.c] = True
        tablero[posicion.f + 1, posicion.c] = True
        
    if posicion.c - 1 < 8 or posicion.c + 1 >= 0 :
        tablero[posicion.f, posicion.c + 1] = True
        tablero[posicion.f, posicion.c - 1] = True        
        
posicion = PosicionTablero(0, 3)
ataque_rey(tablero, posicion)
tablero


array([[False, False,  True,  True,  True, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False]])